### PR TITLE
Add 'testM' and 'testPropertyM' for use with fancier monad stacks

### PR DESCRIPTION
**Pull request by jystic**
Not sure if these should be in their own module perhaps? `Disorder.Core.Monadic`?

! @nhibberd @tranma

### CODE REVIEW

**Comment by charleso** [comment]
I don't think `Disorder.Core.Monadic` or thereabouts can hurt. Not sure whether it should be part of the general `Core` export but would err on the side of not being exported to start with.

Just curious, where/how are we going to use this?

**Comment by jystic** [comment]
I was thinking @nhibberd would need it for this https://github.com/ambiata/amp/pull/117, but will close if it turns out not to be useful. Figured it was better to build `testIO` up from more general pieces rather than just expose the top level thing.

**Comment by charleso** [comment]
> Figured it was better to build testIO up from more general pieces rather than just expose the top level thing.

Cool. Yeah just checking. :)

**Comment by tranma** [comment]
I'm all for not ever writing `monadic` again. Separate module is probably good 📦

**Comment by thumphries** [comment]
Looks like a better default interface 🎲

**Comment by jystic** [comment]
> Just curious, where/how are we going to use this?

I think this is probably better but I can't prove it yet, closing for now, will re-open when I actually need it

**Pull request closed without merging**
