### PR TITLE
Add rudimentary utilities for Haskell-style CLI tests

### PR DESCRIPTION
**Pull request by olorin**
The less shellscript I write, the fewer bugs I find in my code (how odd!) - so I've been writing my CLI tests in Haskell (see e.g., histrionic). What's here now is very rudimetary, so this is more of an RFC on the whole CLI-tests-in-Haskell thing in general.

### CODE REVIEW

**Comment by charleso** [comment]
Personally I'm on the fence, I know I'm a naughty person for using it for tests, but it's been working for the most part. At the same time I agree this is almost certainly a better approach for lots of reasons. I'm happy to defer to others - yes I'm fence sitting.

**Comment by nhibberd** [comment]
Removing bash sounds completely reasonable, not familiar enough with turtle to give a real opinion

**Comment by olorin** [comment]
Yeah, I'm not really familiar with turtle either - I just looked for something with a bunch of shell primitives that made constructing unix-style pipelines fairly intuitive. Definitely open to other suggestions if people have actual preferences.

**Comment by domdere** [comment]
Not a huge fan of either turtle or shelley, we were going to roll our own but it hasnt happened, turtle is probably the best we're going to have *right now*

**Comment by olorin** [comment]
> Personally I'm on the fence, I know I'm a naughty person for using it for tests, but it's been working for the most part. 

Yep, this is true. Two reasons I'd like to use Haskell over bash:

 - Writing bash takes me a lot longer when accounting for the time it takes to actually make it work.
 - Much easier to write property-based CLI tests.

**Comment by olorin** [comment]
> Not a huge fan of either turtle or shelley, we were going to roll our own but it hasnt happened, turtle is probably the best we're going to have right now

Fair enough - I'd certainly want to keep the API clean so that we could switch out turtle for something better if/when it appears.

**Comment by nhibberd** [comment]
Afaik we are just using `process` everywhere else atm. 

/sidenote probably a good idea if someone pulled [mafia process](https://github.com/ambiata/mafia/blob/master/src/Mafia/Process.hs) out to a library :D

**Comment by jystic** [comment]
@nhibberd definitely on my todo list, not sure if there's a clean way to pipe between processes using the API in Mafia.Process, but perhaps it should just be a separate API as the streaming needs tend to overcomplicate situations that don't require it.

**Comment by olorin** [comment]
> Afaik we are just using process everywhere else atm. 

Yeah, `process` might be easier. I went with a shell package in order to mimic actual CLI behaviour as closely as possible, though there aren't many classes of bugs for which that would be necessary to catch. Would you be happier with a set of combinators around `process`?

**Comment by markhibberd** [comment]
@olorin Want to rebase and merge this. I am also on-fence about the best way to test cli / shell-apps. But I don't think there is any problem with exposing this as one way for now. At least it will progress ideas and at some point we can try to centralise on a "best" way, but I don't think it is clear what that is at the moment.

**Comment by olorin** [comment]
Sounds good, shall do.

**Pull request merged**
