### PR TITLE
7.10 compatibility

### PR DESCRIPTION
**Pull request by thumphries**
Renames cabal files to include the ambiata- prefix

Build succeeds with 7.8.4 and 7.10.2 for all modules

edit: couple tests and warnings need updating for 7.10, see below

### CODE REVIEW

**Comment by markhibberd** [comment]
@jystic @tranma @nhibberd @olorin Interested in any other issues we should worry about, but sounds like this is necessary to remove friction around other tooling, so I am :+1: unless there are other concerns.

**Comment by tranma** [comment]
hijacking the thread. @thumphries you didn't run into https://github.com/nick8325/quickcheck/issues/42? I have it on all ghc 7.10.x and quickcheck 2.7.*, looks like it's only fixed in 2.8.*?

**Comment by thumphries** [comment]
Looks like I wasn't building tests, unwittingly, and this shows up when using `$quickcheckAll`. Dang

**Comment by tranma** [comment]
yeah, I think we should move to quickcheck 2.8 anyway. It shouldn't break anything.

**Comment by thumphries** [comment]
Yeah 2.8 bump seems like the way to go

I also missed a bunch of AMP warnings. I wasn't using mafia (didn't know how to build it in 7.10) and they got suppressed. I'll sort em out later today

**Comment by thumphries** [comment]
Fixed the warnings and bumped QuickCheck to 2.8.

Just to make sure I understand things: everything using `disorder` will source it as a submodule and require a manual bump, yes? Otherwise this becomes a more substantial change

**Comment by olorin** [comment]
> Just to make sure I understand things: everything using disorder will source it as a submodule and require a manual bump, yes? Otherwise this becomes a more substantial change

Yep.

Why all the explicit Prelude imports?

**Comment by thumphries** [comment]
Explicit Prelude imports shut up the redundant Applicative / Monoid import warnings in 7.10 without breaking 7.8.

Could also manually enumerate Prelude functions and turn on `NoImplicitPrelude`, or use explicit function names (`import Applicative as A`, `A.pure`) - produces a much noisier PR though

**Comment by thumphries** [comment]
Or use `XCPP` :)

**Comment by olorin** [comment]
> Explicit Prelude imports shut up the redundant Applicative / Monoid import warnings in 7.10 without breaking 7.8.

Hm, why is that? Would not have expected it to make any difference.

Anyway, looks good - :shaved_ice: on rebase + :green_apple:

**Comment by thumphries** [comment]
My understanding is a bit fuzzy, but see https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/UnusedImports#Specfication. The unused imports warn phase will take each symbol and mark the first possible import source as 'used'. We explicitly put Prelude at the bottom, and it goes down that list in order of import. When it comes time to figure out which module gave us Applicative, `Control.Applicative` is chosen as it's higher in the list. I assume an implicit Prelude sits at the top of the list

**Comment by thumphries** [comment]
i.e. it's a hack yes

**Comment by olorin** [comment]
Ah right, sensible. :+1:

**Comment by jystic** [comment]
Is there anything that needs to happen here to get this merged?

**Comment by thumphries** [comment]
nope, just needs another OK

**Comment by olorin** [comment]
Still looks fine to me. :+1:

**Comment by jystic** [comment]
All good dude lgtm, exciting stuff :100:

**Pull request merged**
